Back-End: API to DELETE a Warehouse
SomeViet/instock-project-team-2-server pull request #6
Opened 2022-10-18 02:14 UTC by saint-fox1

2022-10-19 01:16 UTC, ndwilliamson123 requested changes

2022-10-19 01:16 UTC, ndwilliamson123 commented on routes/warehouses.js
> +    res.send(deletedWarehouse);
Need a way to save the updated data to the JSON file for persistence.

```
      fs.writeFile("../data/warehouses.json", JSON.stringify(warehousesList), (err) => {
        if (!err) {
         //successful!
        } else {
         //handle error!
        }
      });

2022-10-19 01:16 UTC, ndwilliamson123 commented on routes/warehouses.js
> +    (warehouse) => warehouse.id === req.params.warehouseId
Like Ankur said today, make sure to do a check here in case the req.params.warehouseId is null/undefined... not sure if the .findIndex method will throw an error even if checking a null/undefined value.

2022-10-21 01:07 UTC, ankurbag approved these changes
Thank you for working on this :) Great job on the error messaging

2022-10-21 01:58 UTC, merged